services:
  - type: web
    name: baserow
    env: docker
    dockerfilePath: render.Dockerfile
    envVars:
    - key: SECRET_KEY
      generateValue: true
    - key: REDIS_URL
      fromService:
        type: redis
        name: baserow-redis
        property: connectionString
    - key: DATABASE_URL
      fromDatabase:  
        name: baserow-db
        property: connectionString
  - type: redis
    name: baserow-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
databases:
  - name: baserow-db
    ipAllowList: [] 